// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XzuuMZBe-9dFHWOlb0zAxyy5D2wF1HM',
    appId: '1:703867063585:web:4dc25976099bc81bb64260',
    messagingSenderId: '703867063585',
    projectId: 'padel03-dev',
    authDomain: 'padel03-dev.firebaseapp.com',
    storageBucket: 'padel03-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSyamwNYOCJ2P-mDfDZNN6oaStuiaij6A',
    appId: '1:703867063585:android:d55e0641bcd4cab5b64260',
    messagingSenderId: '703867063585',
    projectId: 'padel03-dev',
    storageBucket: 'padel03-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80eaiPnhE3Zz3XahTsVwSvu-86Kx0M7w',
    appId: '1:703867063585:ios:9d41c62b5fbf7c11b64260',
    messagingSenderId: '703867063585',
    projectId: 'padel03-dev',
    storageBucket: 'padel03-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterPadel03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA80eaiPnhE3Zz3XahTsVwSvu-86Kx0M7w',
    appId: '1:703867063585:ios:9d41c62b5fbf7c11b64260',
    messagingSenderId: '703867063585',
    projectId: 'padel03-dev',
    storageBucket: 'padel03-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterPadel03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XzuuMZBe-9dFHWOlb0zAxyy5D2wF1HM',
    appId: '1:703867063585:web:0291bf581c01ca47b64260',
    messagingSenderId: '703867063585',
    projectId: 'padel03-dev',
    authDomain: 'padel03-dev.firebaseapp.com',
    storageBucket: 'padel03-dev.firebasestorage.app',
  );
}
