// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa5QW9_stzveoZ6ZGbsbnp0SPq2_jkVuw',
    appId: '1:717241670214:web:25639358c64ff23e6d8847',
    messagingSenderId: '717241670214',
    projectId: 'padel03-staging',
    authDomain: 'padel03-staging.firebaseapp.com',
    storageBucket: 'padel03-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnRynoOk-35wCF-aHhFz8CRJOgL6z4gg',
    appId: '1:717241670214:android:211b72ce0f36c0846d8847',
    messagingSenderId: '717241670214',
    projectId: 'padel03-staging',
    storageBucket: 'padel03-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIetn2u59JXKrwUIEia6I0QgtIzUcLnp4',
    appId: '1:717241670214:ios:be154ec179c8a29c6d8847',
    messagingSenderId: '717241670214',
    projectId: 'padel03-staging',
    storageBucket: 'padel03-staging.firebasestorage.app',
    iosBundleId: 'com.example.flutterPadel03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIetn2u59JXKrwUIEia6I0QgtIzUcLnp4',
    appId: '1:717241670214:ios:be154ec179c8a29c6d8847',
    messagingSenderId: '717241670214',
    projectId: 'padel03-staging',
    storageBucket: 'padel03-staging.firebasestorage.app',
    iosBundleId: 'com.example.flutterPadel03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa5QW9_stzveoZ6ZGbsbnp0SPq2_jkVuw',
    appId: '1:717241670214:web:c5d9e83982365fb66d8847',
    messagingSenderId: '717241670214',
    projectId: 'padel03-staging',
    authDomain: 'padel03-staging.firebaseapp.com',
    storageBucket: 'padel03-staging.firebasestorage.app',
  );
}
