// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5gIpqI43QGJ5D2pIkm08kkb8FkKEzqyc',
    appId: '1:595593582051:android:ea21ae50960ccf0ea0fcd6',
    messagingSenderId: '595593582051',
    projectId: 'padel03-prod',
    authDomain: 'padel03-prod.firebaseapp.com',
    storageBucket: 'padel03-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5gIpqI43QGJ5D2pIkm08kkb8FkKEzqyc',
    appId: '1:595593582051:android:ea21ae50960ccf0ea0fcd6',
    messagingSenderId: '595593582051',
    projectId: 'padel03-prod',
    storageBucket: 'padel03-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyEqfH4y9QLjKaGn7bMbJ3Z8XHK4qL0C7vY2',
    appId: '1:595593582051:ios:16d79a31bc6ee204a0fcd6',
    messagingSenderId: '595593582051',
    projectId: 'padel03-prod',
    storageBucket: 'padel03-prod.appspot.com',
    iosBundleId: 'com.padelarena.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyEqfH4y9QLjKaGn7bMbJ3Z8XHK4qL0C7vY2',
    appId: '1:595593582051:ios:16d79a31bc6ee204a0fcd6',
    messagingSenderId: '595593582051',
    projectId: 'padel03-prod',
    storageBucket: 'padel03-prod.appspot.com',
    iosBundleId: 'com.padelarena.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vY2qfH4y9QLjKaGn7bMbJ3Z8XHK4qL0',
    appId: '1:595593582051:web:84948b1126f96127a0fcd6',
    messagingSenderId: '595593582051',
    projectId: 'padel03-prod',
    authDomain: 'padel03-prod.firebaseapp.com',
    storageBucket: 'padel03-prod.appspot.com',
  );
}